Luc-Mcgrady/Anki-Search-Stats-Extended

readme.md, src/ts/Root.svelte
=> Added: Suspended toggle, Burden -> Load

__init__.py, config.json, readme.md, src/ts/BarScrollable.svelte, src/ts/Candlestick.svelte, src/ts/Candlestick.ts, src/ts/CardDataPies.svelte, src/ts/DueBar.svelte, src/ts/GraphContainer.svelte, src/ts/IntervalPie.svelte, src/ts/IntraDayDueBar.svelte, src/ts/RevlogGraphs.svelte, src/ts/Root.svelte, src/ts/bar.ts, src/ts/config.ts, src/ts/graph.ts, src/ts/index.ts, src/ts/root.ts, src/ts/search.ts, src/ts/stores.ts, src/ts/tooltip.ts
- Time Distribution
- Time Totals
- Review Speed Trend
- Introduced
- Forgotten
- Burden Trend
- Card Count Time Machine
- Review Interval Time Machine
closes #3
=> Feat: Review log graphs

src/ts/stores.ts
=> Fix: Tooltip causes overflow

src/ts/Bar.svelte, src/ts/BarScrollable.svelte, src/ts/Candlestick.svelte, src/ts/CardDataPies.svelte, src/ts/GraphContainer.svelte, src/ts/IntervalPie.svelte, src/ts/bar.ts
=> Graph bounds

config.json, readme.md, src/ts/GraphContainer.svelte, src/ts/Pie.svelte, src/ts/config.ts, src/ts/graph.ts
=> Added: Graph size config

__init__.py, src/ts/search.ts
=> Add Content-Type header to endpoint

__init__.py, config.json, package-lock.json, src/ts/Bar.svelte, src/ts/BarScrollable.svelte, src/ts/Candlestick.svelte, src/ts/Candlestick.ts, src/ts/DayTimings.svelte, src/ts/GraphCategory.svelte, src/ts/GraphContainer.svelte, src/ts/RevlogGraphs.svelte, src/ts/Warning.svelte, src/ts/bar.ts, src/ts/config.ts, src/ts/revlogGraphs.ts, src/ts/root.ts, src/ts/search.ts, src/ts/stores.ts
Respects the users choice to truncate review history.
=> Feat: Respect search date range

src/ts/IntraDayDueBar.svelte
=> Fix: Intra day reviews don't work with empty search string

config.json, package-lock.json, package.json, readme.md, src/ts/Bar.svelte, src/ts/BarScrollable.svelte, src/ts/Candlestick.svelte, src/ts/Candlestick.ts, src/ts/DayTimings.svelte, src/ts/IntervalBar.svelte, src/ts/IntervalGraph.svelte, src/ts/IntraDayDueBar.svelte, src/ts/MatureFilterSelector.svelte, src/ts/RevlogGraphs.svelte, src/ts/TrendValue.svelte, src/ts/bar.ts, src/ts/config.ts, src/ts/revlogGraphs.ts
=> Fatigue + Trend line

__init__.py, src/ts/RevlogGraphs.svelte, src/ts/revlogGraphs.ts, src/ts/search.ts
=> Sibling Trend Graph

src/ts/RevlogGraphs.svelte, src/ts/revlogGraphs.ts
=> Added: Interval rating graph

__init__.py, package-lock.json, package.json, src/ts/MemorisedBar.ts, src/ts/search.ts
wait for https://github.com/open-spaced-repetition/ts-fsrs/pull/146
Disclaim: it cannot estimate cards accurately when their revlogs are incomplete.
=> use fsrs.next_state to estimate memory state accurately

LICENSE, Makefile, package.json, readme.md
Left it a little late. :sweat_smile:
@iamllama @L-M-Sherlock 
Would you mind agreeing to this?
=> Licence under "GPL-3-only"

__init__.py, src/ts/CardDataPies.svelte, src/ts/CardDataPies.ts, src/ts/NoGraph.svelte, src/ts/Root.svelte, src/ts/bar.ts, src/ts/barHelpers.ts, src/ts/config.ts, src/ts/revlogGraphs.ts, src/ts/stores.ts
https://discord.com/channels/368267295601983490/711918918708756481/1332115923284529233
=> Added: Target R as Future due graph

src/ts/MemorisedBar.svelte, src/ts/MemorisedBar.ts, src/ts/bar.ts, src/ts/graph.ts, src/ts/matrix.ts
Adds a b-w matrix under the memorised graph
I'll probably add tool-tips regarding the size of each bin later
=> Added: B-W Matrix

locale/en_GB.ftl, src/ts/MemorisedBar.svelte, src/ts/MemorisedBar.ts, src/ts/RevlogGraphs.svelte, src/ts/bar.ts, src/ts/stores.ts
https://github.com/user-attachments/assets/613d0120-b701-490e-ac75-a3cbc360f0fd
=> Added: Difficulty time machine

locale/en_GB.ftl, src/ts/IntraDayDueBar.svelte, src/ts/RevlogGraphs.svelte, src/ts/bar.ts, src/ts/revlogGraphs.ts
https://github.com/user-attachments/assets/dc7eebc0-1811-4f32-ab7e-42e6d834eb0b
=> Added: Daily hourly breakdown

src/ts/revlogGraphs.ts
=> Fix: Timezones

locale/en_GB.ftl, src/ts/MemorisedBar.svelte, src/ts/MemorisedBar.ts
=> Add notes option to memorised graph

src/ts/MemorisedBar.ts, src/ts/revlogGraphs.ts, src/ts/search.ts, test/revlog.test.ts, test/revlogBuilder.ts
ref:
- https://github.com/ankitects/anki/pull/4063
=> Fix/More robust "forget" detection
